### ISSUE TITLE
Local Dotfiles on Windows?

### ISSUE THREAD

**Issue by abonhote** [paperlib/dotfiles#1]
Hey!

Thanks for this! My config resides in `~\AppData\Local\nvim`, inside `init.lua`. I wonder how you set up your `neovim` to actually use your `.local/dotfiles` path (or `.local\dotfiles`, rather).  Any hint?

Cheers

André

**Comment by paperlib** [comment]
One option for `neovim` on Windows is to configure the xdg [standard paths](https://neovim.io/doc/user/starting.html#_standard-paths) to mimic Unix.

So first set an `XDG_CONFIG_HOME` environment variable to point to `%HOMEPATH%\.config\nvim` and once that's done then just follow the very same "symlinking" as on Unix, ie. using Windows symlink equivalent `mklink` (note one has to open a command prompt as admin to run this one.) So something like:

```
mkdir "%HOMEPATH%\.config\nvim"

mklink    "%HOMEPATH%\.config\nvim\init.vim"     "%HOMEPATH%\.local\dotfiles\.vimrc"
mklink /d "%HOMEPATH%\.config\nvim\colors"       "%HOMEPATH%\.local\dotfiles\.vim\colors"
mklink /d "%HOMEPATH%\.config\nvim\after\plugin" "%HOMEPATH%\.local\dotfiles\.vim\plugin"
```

Actually, I hadn't considered doing it this way earlier (up to now my Windows `neovim` config setup was all "adhoc" `mklinks` and whatnot) but having tried this, it's really nice :+1: will update the readme with the same.

**Comment by abonhote** [comment]
Nice approach, thanks! Can't confirm it works (yet), but give me some more minutes to figure what's wrong.

There's a 

`mkdir "%HOMEPATH%\.config\nvim\after"`

missing - without that, the third `mklink` will fail.

Cheers

André

**Comment by abonhote** [comment]
`nvim -u %XDG_CONFIG_HOME%\init.vim` loads the config, whereas `nvim` doesn't. So apparently the variable still needs some love to be used. Will check later today.

Btw, where did you get that `gruvbox8_hard` colorscheme?

**Comment by paperlib** [comment]
it's really weird that you have to do that `nvim -u` bit. Did you restart your powershell or command prompt after setting that `XDG_CONFIG_HOME` env var? (ie. I have tried this exact setup described above on my Windows laptop and plain `nvim` runs with the configs without the need for that `-u` flag.)

Otherwise the gruvbox theme included there comes from [lifepillar/vim-gruvbox8](https://github.com/lifepillar/vim-gruvbox8).
There are several gruvbox implementations, but chose that one not just because it's fast, rather because as that repo says, it "gracefully degrades to 16, 8 or even only 2 colors", so it works even in fairly limited ancient terminals (it works in macos default terminal and even on Windows plain old classic command prompt!)

**Comment by abonhote** [comment]
Maybe I made some mistake, will re-check on Monday ;-)

**Comment by abonhote** [comment]
Aah, got it working. The problem is that my `XDG_CONFIG_HOME` pointed to `C:\Users\<user>\.config\nvim`. Neovim was looking for `%XDG_CONFIG_HOME%\nvim\init.lua` - which resolves to `...\nvim\nvim\init.lua`. Stripping the `nvim` from the var did the job.
