### ISSUE TITLE
Challenge ;-)

### ISSUE THREAD

**Issue by abonhote** [paperlib/dotfiles#2]
Hey Steph

Challenge for you, maybe you know the solution right away. Is there a way to create a file with a specific pattern if `neovim` is started without opening a file? Like `nvim` without argument would create/open a file like

```
/some/where/<yyyy>-<mm>-<dd>.md
```

This would be awesome. Maybe you have an idea ;-)

Oh, and the file could be based on a template ... ah no, that's Obsidian's task ;-)

Cheers

André

**Comment by paperlib** [comment]
well on that one I just went the "lazy way" and googled it, which turned out this:
[How do I make Vim use a default filename when not given any filenames?](https://vi.stackexchange.com/questions/239/how-do-i-make-vim-use-a-default-filename-when-not-given-any-filenames)
:hugs:

So something like
```
if @% == ""
  let $nameholder = strftime("%Y-%m-%d.md")
  :silent edit $nameholder
endif
```

Otherwise one could play with [autocommands](https://vimhelp.org/autocmd.txt.html) and for example set the name when detecting [a file write event](https://vimhelp.org/autocmd.txt.html#autocmd-events) (eg. [`BufWritePre`](https://vimhelp.org/autocmd.txt.html#BufWritePre)), like assigning some default name, or even prompt for one.

**Comment by abonhote** [comment]
Nice one, thanks! Modified this a bit, works as a charm. Need to get used to the vim language though.
